# Generated by Django 2.1.2 on 2018-10-10 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActorActressList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of the preformer', max_length=50)),
                ('description', models.CharField(help_text='gives information about the preformer', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(help_text="names a movie's title", max_length=100)),
                ('description', models.CharField(help_text='details about a movie, such as ratings, release etc', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Posts made by users below a review', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_title', models.CharField(help_text='A title for the review', max_length=50)),
                ('review', models.TextField(help_text='The body of the review', max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('actor_actress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='movies.ActorActressList')),
                ('authored_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='movies.Movie')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='movies.Review'),
        ),
        migrations.AddField(
            model_name='actoractresslist',
            name='movies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor_actress_list', to='movies.Movie'),
        ),
    ]
