# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-30 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300, unique=True)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='movies.User'),
        ),
        migrations.AlterField(
            model_name='review',
            name='authored_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='movies.User'),
        ),
    ]
