# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-31 22:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MovieWatchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_list_name', models.CharField(help_text=b'The title of the list', max_length=100)),
                ('list_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(help_text=b"The unregistered User's name", max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.ManyToManyField(related_name='movie_category', to='movies.Category'),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie_list', to='movies.MovieWatchList'),
        ),
    ]
