# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-01 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20181101_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_list',
            field=models.ManyToManyField(related_name='movie_list', to='movies.MovieWatchList'),
        ),
    ]
