# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-21 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_remove_movie_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'get_latest_by': 'recently_added'},
        ),
        migrations.RemoveField(
            model_name='moviewatchlist',
            name='list_of_movies',
        ),
        migrations.AddField(
            model_name='movie',
            name='recently_added',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name=b'Created time'),
        ),
        migrations.AlterField(
            model_name='actoractresslist',
            name='description',
            field=models.CharField(help_text=b'gives information about the preformer', max_length=500),
        ),
        migrations.RemoveField(
            model_name='actoractresslist',
            name='movies',
        ),
        migrations.AddField(
            model_name='actoractresslist',
            name='movies',
            field=models.ManyToManyField(related_name='movie', to='movies.Movie'),
        ),
        migrations.AlterField(
            model_name='actoractresslist',
            name='name',
            field=models.CharField(help_text=b'name of the preformer', max_length=300),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.CharField(help_text=b'details about a movie, such as ratings, release etc', max_length=500),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_list',
            field=models.ManyToManyField(related_name='movie_list', to='movies.MovieWatchList'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_title',
            field=models.CharField(help_text=b"names a movie's title", max_length=300),
        ),
        migrations.AlterField(
            model_name='review',
            name='actor_actress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='movies.ActorActressList'),
        ),
    ]
