# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-28 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20181121_2254'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActorActressList',
            new_name='Preformer',
        ),
        migrations.RenameField(
            model_name='preformer',
            old_name='movies',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='review',
            old_name=b'actor_actress',
            new_name='preformer',
        ),
    ]
