# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-06 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_auto_20181128_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_lists',
            field=models.ManyToManyField(blank=True, related_name='movie_list', to='movies.MovieWatchList'),
        ),
    ]
