# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-12 22:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_auto_20181206_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviewatchlist',
            name='movie_list_name',
        ),
    ]
