# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-12 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_remove_moviewatchlist_movie_list_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviewatchlist',
            name='movie_list_name',
            field=models.CharField(blank=True, help_text=b'The title of the list', max_length=100),
        ),
    ]
